//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Fetch
{
    [Serializable]
    public class FetchTrajectoryMsg : Message
    {
        public const string k_RosMessageName = "fetch_msgs/FetchTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public RobotTrajectoryMsg[] trajectory;

        public FetchTrajectoryMsg()
        {
            this.trajectory = new RobotTrajectoryMsg[0];
        }

        public FetchTrajectoryMsg(RobotTrajectoryMsg[] trajectory)
        {
            this.trajectory = trajectory;
        }

        public static FetchTrajectoryMsg Deserialize(MessageDeserializer deserializer) => new FetchTrajectoryMsg(deserializer);

        private FetchTrajectoryMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectory, RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectory);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "FetchTrajectoryMsg: " +
            "\ntrajectory: " + System.String.Join(", ", trajectory.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
