// Generated by gencpp from file fetch_msgs/FetchMoveitJoints.msg
// DO NOT EDIT!


#ifndef FETCH_MSGS_MESSAGE_FETCHMOVEITJOINTS_H
#define FETCH_MSGS_MESSAGE_FETCHMOVEITJOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fetch_msgs
{
template <class ContainerAllocator>
struct FetchMoveitJoints_
{
  typedef FetchMoveitJoints_<ContainerAllocator> Type;

  FetchMoveitJoints_()
    : joints()  {
      joints.assign(0.0);
  }
  FetchMoveitJoints_(const ContainerAllocator& _alloc)
    : joints()  {
  (void)_alloc;
      joints.assign(0.0);
  }



   typedef boost::array<double, 7>  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> const> ConstPtr;

}; // struct FetchMoveitJoints_

typedef ::fetch_msgs::FetchMoveitJoints_<std::allocator<void> > FetchMoveitJoints;

typedef boost::shared_ptr< ::fetch_msgs::FetchMoveitJoints > FetchMoveitJointsPtr;
typedef boost::shared_ptr< ::fetch_msgs::FetchMoveitJoints const> FetchMoveitJointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator1> & lhs, const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator1> & lhs, const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef6b295ba0420f1819e181231006667a";
  }

  static const char* value(const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef6b295ba0420f18ULL;
  static const uint64_t static_value2 = 0x19e181231006667aULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_msgs/FetchMoveitJoints";
  }

  static const char* value(const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[7] joints\n"
;
  }

  static const char* value(const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FetchMoveitJoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator>& v)
  {
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_MSGS_MESSAGE_FETCHMOVEITJOINTS_H
