// Generated by gencpp from file fetch_msgs/MoverServiceRequest.msg
// DO NOT EDIT!


#ifndef FETCH_MSGS_MESSAGE_MOVERSERVICEREQUEST_H
#define FETCH_MSGS_MESSAGE_MOVERSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fetch_msgs/FetchMoveitJoints.h>

namespace fetch_msgs
{
template <class ContainerAllocator>
struct MoverServiceRequest_
{
  typedef MoverServiceRequest_<ContainerAllocator> Type;

  MoverServiceRequest_()
    : joints_input()  {
    }
  MoverServiceRequest_(const ContainerAllocator& _alloc)
    : joints_input(_alloc)  {
  (void)_alloc;
    }



   typedef  ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator>  _joints_input_type;
  _joints_input_type joints_input;





  typedef boost::shared_ptr< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoverServiceRequest_

typedef ::fetch_msgs::MoverServiceRequest_<std::allocator<void> > MoverServiceRequest;

typedef boost::shared_ptr< ::fetch_msgs::MoverServiceRequest > MoverServiceRequestPtr;
typedef boost::shared_ptr< ::fetch_msgs::MoverServiceRequest const> MoverServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator1> & lhs, const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joints_input == rhs.joints_input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator1> & lhs, const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fetch_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e098aa5123a505d98cf51c5fdba8fa47";
  }

  static const char* value(const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe098aa5123a505d9ULL;
  static const uint64_t static_value2 = 0x8cf51c5fdba8fa47ULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_msgs/MoverServiceRequest";
  }

  static const char* value(const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "FetchMoveitJoints joints_input\n"
"\n"
"================================================================================\n"
"MSG: fetch_msgs/FetchMoveitJoints\n"
"float64[7] joints\n"
;
  }

  static const char* value(const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoverServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_msgs::MoverServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fetch_msgs::MoverServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints_input: ";
    s << std::endl;
    Printer< ::fetch_msgs::FetchMoveitJoints_<ContainerAllocator> >::stream(s, indent + "  ", v.joints_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_MSGS_MESSAGE_MOVERSERVICEREQUEST_H
